package com.demo.entity;
// Generated Sep 20, 2021, 7:09:39 AM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.opensymphony.xwork2.validator.annotations.RequiredStringValidator;

/**
 * Accountstruts generated by hbm2java
 */
@Entity
@Table(name = "accountstruts", catalog = "onlinehelpdeskdb")
public class Accountstruts implements java.io.Serializable {

	private Integer id;
	private String username;
	private String password;
	private String fullName;
	private Set<Ticket> tickets = new HashSet<Ticket>(0);

	public Accountstruts() {
	}

	public Accountstruts(String username, String password, String fullName) {
		this.username = username;
		this.password = password;
		this.fullName = fullName;
	}

	public Accountstruts(String username, String password, String fullName, Set<Ticket> tickets) {
		this.username = username;
		this.password = password;
		this.fullName = fullName;
		this.tickets = tickets;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	
	@Column(name = "username", nullable = false, length = 250)
	@RequiredStringValidator(trim = true, key = "errors.required")
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	
	@Column(name = "password", nullable = false, length = 250)
	@RequiredStringValidator(trim = true, key = "errors.required")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "full_name", nullable = false, length = 250)
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountstruts")
	public Set<Ticket> getTickets() {
		return this.tickets;
	}

	public void setTickets(Set<Ticket> tickets) {
		this.tickets = tickets;
	}

}
