package com.demo.entity;
// Generated Sep 20, 2021, 7:09:39 AM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.opensymphony.xwork2.validator.annotations.RequiredStringValidator;

/**
 * Ticket generated by hbm2java
 */
@Entity
@Table(name = "ticket", catalog = "onlinehelpdeskdb")
public class Ticket implements java.io.Serializable {

	private Integer id;
	private Accountstruts accountstruts;
	private Categorystruts categorystruts;
	private Status status;
	private String title;
	private String description;
	private Date createdAt;

	public Ticket() {
	}

	public Ticket(Accountstruts accountstruts, Categorystruts categorystruts, Status status, String title,
			String description, Date createdAt) {
		this.accountstruts = accountstruts;
		this.categorystruts = categorystruts;
		this.status = status;
		this.title = title;
		this.description = description;
		this.createdAt = createdAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id", nullable = false)
	public Accountstruts getAccountstruts() {
		return this.accountstruts;
	}

	public void setAccountstruts(Accountstruts accountstruts) {
		this.accountstruts = accountstruts;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id", nullable = false)
	public Categorystruts getCategorystruts() {
		return this.categorystruts;
	}

	public void setCategorystruts(Categorystruts categorystruts) {
		this.categorystruts = categorystruts;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status_id", nullable = false)
	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	@RequiredStringValidator(trim = true, key = "errors.required")
	@Column(name = "title", nullable = false, length = 250)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}
	
	@RequiredStringValidator(trim = true, key = "errors.required")
	@Column(name = "description", nullable = false, length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_at", nullable = false, length = 10)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

}
